# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lyrics < Formula
  desc "Find and print song lyrics in your terminal"
  homepage "https://github.com/hiroseaki/lyrics-cli"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hiroseaki/lyrics-cli/releases/download/v0.1.1/lyrics_0.1.1_darwin_amd64.tar.gz"
      sha256 "0dc2bc036e8039cebe0e21312986ae6da4c17753c7482365dab2d115926fcace"

      define_method(:install) do
        bin.install "lyrics"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hiroseaki/lyrics-cli/releases/download/v0.1.1/lyrics_0.1.1_darwin_arm64.tar.gz"
      sha256 "6339193a5c609a7fedd320ac7842e258f7da18552fae6d4765702444834ee2b4"

      define_method(:install) do
        bin.install "lyrics"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hiroseaki/lyrics-cli/releases/download/v0.1.1/lyrics_0.1.1_linux_amd64.tar.gz"
      sha256 "da81d8d99fcfb25ea3eba82b478f3ec02c21ccc0b7be27dc3ea3c52e1470b230"
      define_method(:install) do
        bin.install "lyrics"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hiroseaki/lyrics-cli/releases/download/v0.1.1/lyrics_0.1.1_linux_arm64.tar.gz"
      sha256 "ea0e468c5ec66607af5a077743a922d1107b2a2f83475720adb7ec6a1bf3814f"
      define_method(:install) do
        bin.install "lyrics"
      end
    end
  end
end
