# This file was generated by GoReleaser. DO NOT EDIT.
cask "lyrics" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "4bddd86e23d6f81b39d8a8e0ab63e7cd7d9d69eb13472cab7837bfec108c621e"
      url "https://github.com/hiroseaki/lyrics-cli/releases/download/v#{version}/lyrics_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "2d1ea37e2c0076f879de17f33c2af3f4d2efe32f3fd093bbcc72f1715e862fe8"
      url "https://github.com/hiroseaki/lyrics-cli/releases/download/v#{version}/lyrics_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "7a6e24a65181c3dabb4d86d628d96bb8883b70e08ea1ada6238fa7171d8229b5"
      url "https://github.com/hiroseaki/lyrics-cli/releases/download/v#{version}/lyrics_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "ba0184ea05e50e503e04582eaaab35e6a3630ccdb53fff7549c562349280fa09"
      url "https://github.com/hiroseaki/lyrics-cli/releases/download/v#{version}/lyrics_#{version}_linux_arm64.tar.gz"
    end
  end

  name "lyrics"
  desc "Find and print song lyrics in your terminal"
  homepage "https://github.com/hiroseaki/lyrics-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lyrics"

  # No zap stanza required

end
